### ISSUE TITLE
第一回 🍱

### ISSUE THREAD

**Issue by risacan** [ikejirirb/POODR#1]
# 範囲！
* p3 ~ p27
* はじめに
* はしがき
* 1.1 設計の賞賛
* 1.2 設計の道具
* 1.3 設計の行為

# すすめかた！
* 読み終わったら、このIssueのコメント欄で、[読み終わった宣言]をする！ 🎉 
* 気になったキーワードとかは、ここのIssueのコメントにメモ！:memo: 

# 🍱 
* 3/3 🎎

**Comment by risacan** [comment]
@katorie 
上記なかんじでどうでしょう！多いか少ないかわからないので、20ページ前後できり良さそうな感じにしました。
多いなって感じだったらまた調整しましょう 👍 
すすめかたも、つっこみドンドンよろしくお願いします 🙌

**Comment by katorie** [comment]
@risacan
反応遅くなってごめんなさい💦 下準備ありがとうございます😘😘😘
やりながら軌道修正したりしてすすめましょう✨
読みはじめます📚

**Comment by risacan** [comment]
第二回への反省
* 気になった箇所さきに書いておく（ @risacan ）
* もうちょっと読めそう
* 👶 いると、大勢ではむりなので、二人くらいがヨサそう

**Comment by ppworks** [comment]
読み始めたので、こっそり追っていく。 😎 

> p.21
> 実用的な設計とは、未来を推測するものではなく、**未来を受け入れるための選択肢を保護する**ものなのです。

> p.29
> 妥協をして設計をすることは、いわば未来から時間を借りているようなものです。これは「技術的負債」として知られています。技術的負債は貸し付けであり、いずれ返さなければなりません。**往々にして利子もつく**のですが。

> p.33
> 同じ設計努力で最大限の成果を得る秘訣は、設計理論を**理解し**、それらの理論を**適切に使う**ことです。

**Comment by ppworks** [comment]
👀
